name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
      tag_name: ${{ steps.set_tag.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set tag name
        id: set_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            TAG_NAME="v$(date +'%Y.%m.%d')-build.${{ github.run_number }}"
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git tag $TAG_NAME
            git push origin $TAG_NAME || true
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag.outputs.tag_name }}
          release_name: Syshardn Desktop ${{ steps.set_tag.outputs.tag_name }}
          body: |
            Desktop application for Syshardn system hardening tool.
            
            **Build Info:**
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            
            **Downloads:**
            - macOS: `.dmg` file
            - Linux: `.AppImage`, `.deb`, or `.rpm` file
            - Windows: `.exe` installer
            
            See [README](https://github.com/Aswinr24/syshardn-desktop/blob/main/README.md) for installation instructions.
          draft: false
          prerelease: false

  build:
    needs: create-release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Prepare Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full xz-utils libfuse2 fakeroot rpm dpkg-dev
          sudo snap install snapcraft --classic || true
          if [ -f node_modules/app-builder-bin/linux/x64/app-builder ]; then
            chmod +x node_modules/app-builder-bin/linux/x64/app-builder || true
          fi
          rm -rf ~/.cache/electron-builder || true

      - name: Build and Release
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run build:mac
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            npm run build:linux
          else
            npm run build:win
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: |
            dist/*.dmg
            dist/*.zip
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.exe
            dist/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
